### ISSUE TITLE
Сделать сервер 

### ISSUE THREAD

**Issue by GloomlySeth** [GloomlySeth/Chikenator#5]
1.	Регистрация новых пользователей, с заранее установленными правами
2.	Возможности учетной записи администратора : 
2.1 создание/удаление новых ролей, присвоение им прав (на удаление, добавление,  изменение, и т.д)
2.2 установка ограничений для групп пользователей или для конкретных пользователей (например не более 2 курятников/датчиков полива или др.)
3. Возможность добавления действий по расписанию (например 18:00 насыпать корм, 19:00 выключить свет и т.д)
4. Ручное управление модулями
5. Потоковое вещание видео с камер(ы), ее управление
6. (опционально) Конвертация видео, с нескольких потоков, в один (4 квадратика в одном)
7. Хранение в БД всех настроек и разрешений

**Comment by freedom00000** [comment]
Примерный json
{"User":{"UserId":203,"RoleId":1,"CoopId":"413789","Name":"Petyshok Pyotr Specnaz"},"Role":{"Id":3,"RoleName":"Admin"},"settingsCoop":{"Doors":{"State":false,"OpenByTime":false,"OpenByDaylight":false,"OpenTime":"10:00:00","CloseTime":"11:00:00","TempMore":0,"TempLess":0},"Heating":{"Test":false,"SwitchOn":10,"SwitchOff":15},"Light":{"Switch":false,"OpenByTime":false,"OpenBySensor":false,"OpenFrom":"10:00:00","CloseBefore":"11:00:00"}}}

**Comment by freedom00000** [comment]
После подключения к серверу необходимо прислать json следующего образца
Для мобильника:
```
{"Autorization":{"Who":"mobile","UserName":"TEST","Password":"test","CoopId":"2","Action":"state"}}
```
Для курятника:
```
{"Autorization":{"Who":"coop","CoopId":"2"}}
```
где Who - coop(курятник) или mobile (мобильник),
UserName и - Password поле обязательное только для мобильника
CoopId - id курятника
Action - поле обязательное только для мобильника, может принимать значения state , video , change_settings , get_settings, get_coops, sign_up, recover, change_pass

**Comment by freedom00000** [comment]
Ответ на Action : "state"
```
{"Light":true,"Feed":1,"Water":1,"TempWater":1,"TempIn":1,"TempOut":1,"Vent":true,"Door":false,"Heating":false, "Humidity":"50"}
```

**Comment by freedom00000** [comment]
Ответ на Action : "get_settings"
```
{"Debug":"0",
"Doors":
{"Debug":"0","OpenByTime":true,"OpenByDaylight":true,"OpenTime":"05:54:00","CloseTime":"11:03:00","TempMore":19,"TempLess":31},
"Heating":
{"Debug":"0","SwitchOn":"23","SwitchOff":"23"},
"Light":
{"Debug":"0","OpenByTime":false,"OpenBySensor":true,"OpenFrom":"05:00:00","CloseBefore":"12:12:00"},"
Vent":
{"Debug":"0","TimeOn":"38","TimeOff":"41","TempThreshold":" 21","TimeMode":" 0"}}
```

**Comment by freedom00000** [comment]
Для обновления настроек:
Action:"change_settings"
Пример:
```
{"Debug":"0","Doors":
{"Debug":"0","OpenByTime":false,"OpenByDaylight":true,"OpenTime":"10:00","CloseTime":"13:37",
"TempMore":14,"TempLess":88},"Heating":{"Debug":"0","SwitchOn":"32","SwitchOff":"33"},"Light":
{"Debug":"0","OpenByTime":false,"OpenBySensor":true,"OpenFrom":"2","CloseBefore":"1"},"Vent":
{"Debug":"0","TimeOn":"1","TimeOff":"2","TempThreshold":"33","TimeMode":"1"},"Autorization":
{"Who":"mobile","UserName":"TEST","Password":"test","CoopId":2,"Action":"change_settings"}}

```
если успешно придет "OK" , если нет "ERROR"

**Comment by freedom00000** [comment]
Так как по условиям задачи у одного пользователя может быть несколько курятников, то чтобы узнать id курятников принадлежащих юзеру, необходимо отправить action get_coops
Пример:
```
{"Autorization":{"Who":"mobile","UserName":"TEST","Password":"test","Action":"get_coops"}}


```
Ответом будет массив курятников вида:
```
[{"Id":"1","Name":"adminsky"},{"Id":"2","Name":"testovi"}]
```

**Comment by buble** [comment]
Текущие проблемы:

- надо также получать Humidity для Action = state
- неправильный тип данных для обогрева 
Heating":{"Test":true,"SwitchOn":"00:00:25","SwitchOff":"00:00:25"}
для SwitchOn и SwitchOff нужны температуры
- в JSON настроек отсутствует секция Ventilation
требуется обновление для get_settings и change_settings

**Comment by freedom00000** [comment]
Для регистрации Action: "sign_up", в поле Who новое имя курятника.
Пример:
```
{"Autorization":{"Who":"kuriatnick","UserName":"TEST","Password":"test","CoopId":"2","Action":"sign_up"}}

```

**Comment by freedom00000** [comment]
Для восстановления пароля:
Проверка на возможность сброса пароля Action: "recover", в значении Who отправить название курятника
Пример:
```
{"Autorization":{"Who":"testovi","UserName":"TEST","CoopId":"2","Action":"recover"}}

```
При ответе "success" можно отправить запрос на смену Action: "change_pass"
Пример:
```
{"Autorization":{"UserName":"TEST","Password":"test","Action":"change_pass"}}

```
